version: '3.4'
services:
  authoring:
    image: bcanvural/myproject-authoring:0.1.0-SNAPSHOT
    ports:
      - "8081:8080"
    links:
      - db
    environment:
      profile: postgres
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: mypass
      POSTGRES_DB_NAME: brxmdb
      POSTGRES_WPM_DB_NAME: wpmdb
      POSTGRES_DB_DRIVER: org.postgresql.Driver
      REPO_WORKSPACE_BUNDLE_CACHE: 256
      REPO_VERSIONING_BUNDLE_CACHE: 64
      REPO_BOOTSTRAP: "true"
    depends_on:
      - db
  delivery:
    image: bcanvural/myproject-delivery:0.1.0-SNAPSHOT
    user: root
    ports:
      - "8082:8080"
      - "5005:5005"
    links:
      - db
    environment:
      profile: postgres
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: mypass
      POSTGRES_DB_NAME: brxmdb
      POSTGRES_WPM_DB_NAME: wpmdb
      POSTGRES_DB_DRIVER: org.postgresql.Driver
      REPO_WORKSPACE_BUNDLE_CACHE: 256
      REPO_VERSIONING_BUNDLE_CACHE: 64
      REPO_BOOTSTRAP: "false"
      JAVA_ENABLE_DEBUG: "true"
    volumes:
      - ./curl_till_200.sh:/brxm/curl_till_200.sh
    depends_on:
      - db
      - authoring
    entrypoint: ["sh", "-c", "/brxm/curl_till_200.sh && /brxm/bin/docker-entrypoint.sh"]
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: postgres
    volumes:
      - ./brxmdb.sql:/docker-entrypoint-initdb.d/brxmdb.sql
      - ./wpmdb.sql:/docker-entrypoint-initdb.d/wpmdb.sql